# This file is inspired on
# https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
FROM {{baseImage}}

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 8080
CMD [ "node", "." ]
